CREATE DATABASE IF NOT EXISTS decampoacampo;

USE decampoacampo;

CREATE TABLE IF NOT EXISTS productos
(
    id          INT PRIMARY KEY AUTO_INCREMENT,
    nombre      VARCHAR(255)   NOT NULL,
    descripcion TEXT,
    precio      DECIMAL(10, 2) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
